name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run tests with Maven
        run: mvn -B clean test

      - name: Auto Merge PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'development' && success() }}
        uses: peter-evans/auto-merge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
